# 1. Scrape the details of most viewed videos on YouTube from Wikipedia:

- Url= https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
- You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [9]:
#Importing reqiured libraries
import selenium
import pandas as pd
from selenium import webdriver
import requests
import re
from bs4 import BeautifulSoup

#For eliminating all the warnings
import warnings
warnings.filterwarnings('ignore')

In [10]:
import time
from selenium.webdriver.common.keys import Keys

#Import Exceptions that we might require handling
from selenium.common.exceptions import StaleElementReferenceException
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.common.exceptions import TimeoutException
from datetime import datetime

In [11]:
#Connecting to web driver
driver = webdriver.Chrome(r"C://chromedriver.exe")
driver.maximize_window()

In [12]:
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')
driver.implicitly_wait(5)

In [13]:
#Creating empty lists for storing scraped data
Rank=[]
Name=[]
Artist=[]
Views=[]
UD=[]

In [14]:
#Collecting the information of most viewed songs on Wikipedia
rank = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[1]')
for i in rank:
    Rank.append(i.text)
name = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[2]')
for i in name:
    Name.append(i.text)
artist = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[3]')
for i in artist:
    Artist.append(i.text)
view = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[4]')
for i in view:
    Views.append(i.text)
date = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[5]')
for i in date:
    UD.append(i.text)

In [15]:
#Creating Dataframe for storing the collected data present in lists
Top_Vid = pd.DataFrame({})
Top_Vid['Rank']=Rank[0:30]
Top_Vid['Video Name']=Name[0:30]
Top_Vid['Artist']=Artist[0:30]
Top_Vid['Views (in Billions)']=Views[0:30]
Top_Vid['Upload Date']=UD[0:30]

In [16]:
Top_Vid

,Rank,Video Name,Artist,Views (in Billions),Upload Date
0,1.,"""Baby Shark Dance""[22]",Pinkfong Kids' Songs & Stories,8.50,"June 17, 2016"
1,2.,"""Despacito""[24]",Luis Fonsi,7.33,"January 12, 2017"
2,3.,"""Shape of You""[25]",Ed Sheeran,5.30,"January 30, 2017"
3,4.,"""Johny Johny Yes Papa""[26]",LooLoo Kids,5.27,"October 8, 2016"
4,5.,"""See You Again""[27]",Wiz Khalifa,5.09,"April 6, 2015"
5,6.,"""Masha and the Bear – Recipe for Disaster""[30]",Get Movies,4.43,"January 31, 2012"
6,7.,"""Uptown Funk""[31]",Mark Ronson,4.17,"November 19, 2014"
7,8.,"""Gangnam Style""[32]",Psy,4.06,"July 15, 2012"
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[34]",Miroshka TV,4.01,"February 27, 2018"
9,10.,"""Bath Song""[35]",Cocomelon – Nursery Rhymes,3.99,"May 2, 2018"
10,11.,"""Phonics Song with Two Words""[36]",ChuChu TV,3.81,"March 6, 2014"
11,12.,"""Sugar""[37]",Maroon 5,3.45,"January 14, 2015"
12,13.,"""Sorry""[38]",Justin Bieber,3.43,"October 22, 2015"
13,14.,"""Roar""[39]",Katy Perry,3.34,"September 5, 2013"
14,15.,"""Dame Tu Cosita""[40]",El Chombo,3.30,"April 5, 2018"
15,16.,"""Counting Stars""[41]",OneRepublic,3.28,"May 31, 2013"
16,17.,"""Thinking Out Loud""[42]",Ed Sheeran,3.25,"October 7, 2014"
17,18.,"""Dark Horse""[43]",Katy Perry,3.06,"February 20, 2014"
18,19.,"""Faded""[44]",Alan Walker,3.05,"December 3, 2015"
19,20.,"""Shake It Off""[45]",Taylor Swift,3.05,"August 18, 2014"
20,21.,"""Lean On""[46]",Major Lazer Official,3.03,"March 22, 2015"
21,22.,"""Bailando""[47]",Enrique Iglesias,3.02,"April 11, 2014"
22,23.,"""Girls Like You""[48]",Maroon 5,3.02,"May 31, 2018"
23,24.,"""Let Her Go""[49]",Passenger,2.98,"July 25, 2012"
24,25.,"""Wheels on the Bus""[50]",Cocomelon – Nursery Rhymes,2.94,"May 24, 2018"
25,26.,"""Mi Gente""[51]",J Balvin,2.91,"June 29, 2017"
26,27.,"""Perfect""[52]",Ed Sheeran,2.83,"November 9, 2017"
27,28.,"""Hello""[53]",Adele,2.83,"October 22, 2015"
28,29.,"""Waka Waka (This Time for Africa)""[54]",Shakira,2.81,"June 4, 2010"
29,30.,"""Axel F""[55]",Crazy Frog,2.78,"June 16, 2009"

# 2. Scrape the details team India’s international fixtures from bcci.tv.

- Url = https://www.bcci.tv/.
- You need to find following details:
A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time

In [25]:
#Connecting to web driver
driver = webdriver.Chrome(r"C://chromedriver.exe")
driver.maximize_window()

In [26]:
#Opening Bccitv page
driver.get('https://www.bcci.tv/')
driver.implicitly_wait(5)

In [27]:
#Opening Fixtures from International drop down menu
infix=driver.find_element_by_xpath("//ul[@class='navigation__list showMoreEnabled']/li[1]/div[2]/div/ul/li[1]/a")
driver.get(infix.get_attribute('href'))

In [42]:
#Creating empty lists for storing scraped data
Title = []
Series = []
Place = []
Date = []
Time = []

In [43]:
#Collecting the information of International fixtures from bcci site
title = driver.find_elements_by_xpath('//strong[@class="fixture__name fixture__name--with-margin"]')
for i in title:
    Title.append(i.text)
series = driver.find_elements_by_xpath('//div[@class="fixture__format-strip"]/span[2]')
for i in series:
    Series.append(i.text)
place = driver.find_elements_by_xpath('//p[@class="fixture__additional-info"]/span')
for i in place:
    Place.append(i.text)
date = driver.find_elements_by_xpath('//div[@class="fixture__datetime desktop-only"]/div/span')
month = driver.find_elements_by_xpath('//div[@class="fixture__datetime desktop-only"]/div/div/span[1]')
for i in range(len(date)):
    Date.append(date[i].text+month[i].text)
time = driver.find_elements_by_xpath('//div[@class="fixture__datetime desktop-only"]/div/div/span[2]')
for i in time:
    Time.append(i.text)

In [44]:
#Creating Dataframe for storing the collected data present in lists
bcci_fix = pd.DataFrame({})
bcci_fix['Match Details'] = Title
bcci_fix['Series'] = Series
bcci_fix['Venue'] = Place
bcci_fix['Date'] = Date
bcci_fix['Time'] = Time

In [45]:
bcci_fix

,Match Details,Series,Venue,Date,Time
0,Final,ICC WORLD TEST CHAMPIONSHIP FINAL,"The Ageas Bowl, Southampton",,
1,1st Test,ENGLAND V INDIA 2021,"Trent Bridge, Nottingham",,
2,2nd Test,ENGLAND V INDIA 2021,"Lord's, London",,
3,3rd Test,ENGLAND V INDIA 2021,"Headingley, Leeds",,
4,4th Test,ENGLAND V INDIA 2021,"The Oval, London",,
5,5th Test,ENGLAND V INDIA 2021,"Old Trafford, Manchester",,

# 3. Scrape the details of selenium exception from guru99.com.

- Url = https://www.guru99.com/
- You need to find following details:
A) Name
B) Description
- Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [48]:
#Connecting to web driver
driver = webdriver.Chrome(r"C://chromedriver.exe")
driver.maximize_window()

In [49]:
#Opening Guru99 page
driver.get('https://www.guru99.com/')
driver.implicitly_wait(5)

In [50]:
#Opening through Selenium icon
driver.find_element_by_xpath("//div[@class='srch']/span[8]/a").click()

In [51]:
# Let's click on the selenium exception tutorial link
driver.find_element_by_xpath("//table[@class='table']/tbody/tr[34]/td/a").click()

In [52]:
#Creating empty lists for storing scraped data
Name=[]
Description=[]

In [53]:
#Collecting the information of Selenium from guru99 site
name = driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[1]')
for i in name:
    Name.append(i.text)
description = driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[2]')
for i in description:
    Description.append(i.text)

In [54]:
#Creating Dataframe for storing the collected data present in lists
guru_sel=pd.DataFrame({})
guru_sel['Exception Name']=Name[1:]
guru_sel['Description']=Description[1:]
guru_sel

,Exception Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can't be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

# 4. Scrape the details of State-wise GDP of India from statisticstime.com.

- Url = http://statisticstimes.com/
- You have to find following details:
A) Rank
B) State
C) GSDP(18-19)
D) GSDP(17-18)
E) Share(2017)
F) GDP($ billion)
- Note: - From statisticstimes home page you have to reach to economy page through code.

In [62]:
#Connecting to web driver
driver = webdriver.Chrome(r"C://chromedriver.exe")
driver.maximize_window()

In [63]:
#Opening statistictmes page
driver.get('http://statisticstimes.com/')
driver.implicitly_wait(5)

In [64]:
#Finding GDP of India
Economy_India=driver.find_element_by_xpath("//div[@class='navbar']/div[2]/div/a[3]")
driver.get(Economy_India.get_attribute('href'))

In [65]:
#Finding GDP of Indian states
GDP_Indian_States=driver.find_element_by_xpath("//div[@style='float:left;background-color:seashell;width:400px;height:800px;']/ul/li[1]/a")
driver.get(GDP_Indian_States.get_attribute('href'))

In [66]:
#Creating empty lists for storing scraped data
Rank=[] 
State=[] 
GSDP1=[] 
GSDP2=[] 
SYear=[] 
GDP=[]

In [67]:
#Collecting the information of GDP of Indian states from statistictimes site
rank = driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[1]')
for i in rank:
    Rank.append(i.text)
state = driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[2]')
for i in state:
    State.append(i.text)
gdsp1 = driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[3]')
for i in gdsp1:
    GSDP1.append(i.text)
gdsp2 = driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[4]')
for i in gdsp2:
    GSDP2.append(i.text)
share = driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[5]')
for i in share:
    SYear.append(i.text)
gdp = driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[6]')
for i in gdp:
    GDP.append(i.text)

In [71]:
#Creating Dataframe for storing the collected data present in lists
stat_gdp = pd.DataFrame({})
stat_gdp['Rank'] = Rank
stat_gdp['State Name'] = State
stat_gdp['GSDP(18-19)'] = GSDP1
stat_gdp['GSDP(17-18)'] = GSDP2
stat_gdp['Share'] = SYear
stat_gdp['GDP(Billion $)'] = GDP

In [72]:
stat_gdp

,Rank,State Name,GSDP(18-19),GSDP(17-18),Share,GDP(Billion $)
0,1,Maharashtra,-,"2,632,792",13.88%,398.145
1,2,Tamil Nadu,"1,845,853","1,630,208",8.59%,246.529
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.35%,239.656
3,4,Gujarat,-,"1,502,899",7.92%,227.276
4,5,Karnataka,"1,631,977","1,493,127",7.87%,225.798
5,6,West Bengal,"1,253,832","1,089,898",5.75%,164.820
6,7,Rajasthan,"1,020,989","942,586",4.97%,142.543
7,8,Andhra Pradesh,"972,782","862,957",4.55%,130.501
8,9,Telangana,"969,604","861,031",4.54%,130.210
9,10,Madhya Pradesh,"906,672","809,592",4.27%,122.431
10,11,Kerala,-,"781,653",4.12%,118.206
11,12,Delhi,"856,112","774,870",4.08%,117.180
12,13,Haryana,"831,610","734,163",3.87%,111.024
13,14,Bihar,"611,804","530,363",2.80%,80.204
14,15,Punjab,"574,760","526,376",2.77%,79.601
15,16,Odisha,"521,275","487,805",2.57%,73.768
16,17,Assam,-,"315,881",1.67%,47.769
17,18,Chhattisgarh,"329,180","304,063",1.60%,45.982
18,19,Jharkhand,"328,598","297,204",1.57%,44.945
19,20,Uttarakhand,-,"245,895",1.30%,37.186
20,21,Jammu & Kashmir,-,"155,956",0.82%,23.584
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.265
22,23,Goa,"80,449","73,170",0.39%,11.065
23,24,Tripura,"55,984","49,845",0.26%,7.538
24,25,Chandigarh,-,"42,114",0.22%,6.369
25,26,Puducherry,"38,253","34,433",0.18%,5.207
26,27,Meghalaya,"36,572","33,481",0.18%,5.063
27,28,Sikkim,"32,496","28,723",0.15%,4.344
28,29,Manipur,"31,790","27,870",0.15%,4.215
29,30,Nagaland,-,"27,283",0.14%,4.126
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.721
31,32,Mizoram,"26,503","22,287",0.12%,3.370
32,33,Andaman & Nicobar Islands,-,-,-,-

# 5. Scrape the details of trending repositories on Github.com.

- Url = https://github.com/
- You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [76]:
from selenium.common.exceptions import ElementNotInteractableException

In [73]:
#Connecting to web driver
driver = webdriver.Chrome(r"C://chromedriver.exe")
driver.maximize_window()

In [74]:
#Opening GitHub page
driver.get('https://github.com/')
driver.implicitly_wait(5)

In [77]:
#Opening Trending page by choosing Explore Menu
trend=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul[2]/li[3]/a")
try:
    trend.click()
except ElementNotInteractableException:
    driver.get(trend.get_attribute('href'))

In [79]:
#Creating empty lists for storing scraped data
Rep_Title=[]
Rep_Desc=[] 
CC=[] 
Lang=[]
urls=[]

In [80]:
#Collecting the information of top trending repos. from GitHub
rep_title=driver.find_elements_by_xpath('//article[@class="Box-row"]/h1/a')
desc=driver.find_elements_by_xpath('//article[@class="Box-row"]/p')
for i in [rep_title,desc]:
    for j in i:
        if i ==rep_title:
            Rep_Title.append(j.text)
            urls.append(j.get_attribute('href'))
        if i==desc:
            Rep_Desc.append(j.text)
for url in urls:
    driver.get(url)
    driver.implicitly_wait(3)
    div_list=driver.find_elements_by_xpath('//div[@class="BorderGrid BorderGrid--spacious"]/div')
    try:
        CC.append(((div_list[-2].text).split())[1])
    except:
        CC.append('-----')
    try:
        Lang.append(((div_list[-1].text).split())[1::2])
    except:
        Lang.append('-----')

In [83]:
#Creating Dataframe for storing the collected data present in lists
Git_Tre = pd.DataFrame({})
Git_Tre['Repository Title']=Rep_Title[0:24]
Git_Tre['Repository Description']=Rep_Desc[0:24]
Git_Tre['Contributors']=CC[0:24]
Git_Tre['Language Used']=Lang[0:24]

In [84]:
Git_Tre

,Repository Title,Repository Description,Contributors,Language Used
0,slidevjs / slidev,Presentation Slides for Developers (Public Bet...,17,"[TypeScript, Vue, CSS, JavaScript, HTML]"
1,Renovamen / playground-macos,"My portfolio website simulating macOS's GUI, d...",2,"[JavaScript, CSS, HTML]"
2,Chia-Network / chia-blockchain,Chia blockchain python implementation (full no...,61,"[Python, Other]"
3,sundowndev / phoneinfoga,Information gathering & OSINT framework for ph...,9,"[Go, Vue, JavaScript, TypeScript, Shell, Docke..."
4,dogecoin / dogecoin,very currency,202,"[C++, Python, C, M4, Makefile, HTML, Other]"
5,youngyangyang04 / leetcode-master,LeetCode 刷题攻略：200道题目刷题顺序，共60w字的详细图解，视频难点剖析，50余...,No,[5]
6,abuanwar072 / Flutter-Responsive-Admin-Panel-o...,Responsive Admin Panel or Dashboard using Flutter,-----,"[Dart, Ruby, HTML, Swift, Other]"
7,30-seconds / 30-seconds-of-code,Short JavaScript code snippets for all your de...,257,[JavaScript]
8,Light-City / CPlusPlusThings,C++那些事,20,"[C++, Other]"
9,microsoft / Web-Dev-For-Beginners,"24 Lessons, 12 Weeks, Get Started as a Web Dev...",62,"[JavaScript, HTML, CSS, Vue]"
10,google / zx,A tool for writing better scripts,7,[JavaScript]
11,rustdesk / rustdesk,The best open source remote desktop client sof...,4,"[Rust, CSS, C++, Other]"
12,trimstray / the-book-of-secret-knowledge,"A collection of inspiring lists, manuals, chea...",-----,"[80, 69]"
13,donnemartin / system-design-primer,Learn how to design large-scale systems. Prep ...,110,"[Python, Shell]"
14,ossrs / srs,"SRS is a simple, high efficiency and realtime ...",38,"[C++, HTML, JavaScript, ActionScript, C, Shell..."
15,lucidrains / x-transformers,A simple but complete full-attention transform...,4,[Python]
16,TheAlgorithms / C-Plus-Plus,Collection of various algorithms in mathematic...,218,"[C++, CMake]"
17,discordjs / discord.js,A powerful JavaScript library for interacting ...,289,"[JavaScript, TypeScript]"
18,home-assistant / core,🏡 Open source home automation that puts local ...,"2,444",[Python]
19,dromara / shenyu,High-Performance Java API Gateway,155,"[Java, Other]"
20,devsuperior / sds3,"A cross-platform, OpenGL terminal emulator.",No,"[No, published]"
21,alacritty / alacritty,🔗 Some useful websites for programmers.,330,"[Rust, Shell, Other]"
22,sdmg15 / Best-websites-a-programmer-should-visit,Everything you need to prepare for your techni...,No,"[210, 199]"
23,Olshansk / interview,🔎 Hunt down social media accounts by username ...,-----,"[27, 16]"

# 6. Scrape the details of top 100 songs on billiboard.com.

- Url = https://www.billboard.com/
- You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
- Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [85]:
#Connecting to web driver
driver = webdriver.Chrome(r"C://chromedriver.exe")
driver.maximize_window()

In [88]:
#Opening Billboard page
driver.get('https://www.billboard.com/')
driver.implicitly_wait(5)

In [89]:
#Opening Top 100 songs by choosing Full Chart in Top songs
driver.find_element_by_xpath("//nav[@class='header__subnav bg--light']/ul/li[3]/a").click()

In [90]:
#Creating empty lists for storing scraped data
SName=[]
AName=[] 
LRank=[] 
PRank=[]
Weeks=[]

In [91]:
#Collecting the information of top 100 songs from Billboard
song = driver.find_elements_by_xpath('//span[@class="chart-element__information__song text--truncate color--primary"]')
for i in song:
    SName.append(i.text)
artist = driver.find_elements_by_xpath('//span[@class="chart-element__information__artist text--truncate color--secondary"]')
for i in artist:
    AName.append(i.text)
lastweek = driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--last"]')
for i in lastweek:
    LRank.append(i.text)
peak = driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--peak"]')
for i in peak:
    PRank.append(i.text)
weeks = driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--week"]')
for i in weeks:
    Weeks.append(i.text)

In [92]:
#Creating Dataframe for storing the collected data present in lists
BillTop=pd.DataFrame({})
BillTop['Song']=SName
BillTop['Artist']=AName
BillTop['Last Week Rank']=LRank
BillTop['Peak Rank']=PRank
BillTop['Weeks on Billboard']= Weeks

In [93]:
BillTop

,Song,Artist,Last Week Rank,Peak Rank,Weeks on Billboard
0,Save Your Tears,The Weeknd & Ariana Grande,6,1,20
1,Leave The Door Open,Silk Sonic (Bruno Mars & Anderson .Paak),2,1,8
2,Peaches,Justin Bieber Featuring Daniel Caesar & Giveon,3,1,6
3,Rapstar,Polo G,1,1,3
4,Levitating,Dua Lipa Featuring DaBaby,5,5,30
...,...,...,...,...,...
95,4 Da Gang,42 Dugg & Roddy Ricch,100,67,4
96,Blame It On You,Jason Aldean,-,97,1
97,Wasted On You,Morgan Wallen,92,9,16
98,Way Less Sad,AJR,-,99,1
99,Clear Da Air,Moneybagg Yo,-,100,1

# 7. Scrape the details of Data science recruiters from naukri.com.

- Url = https://www.naukri.com/
- You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
- Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [94]:
#Connecting to web driver
driver = webdriver.Chrome(r"C://chromedriver.exe")
driver.maximize_window()

In [95]:
#Opening Naukri.com page
driver.get('https://www.naukri.com/')
driver.implicitly_wait(5)

In [96]:
#Clicking on the recruiter option
rec=driver.find_element_by_xpath("//ul[@class='midSec menu']/li[2]/a")
driver.get(rec.get_attribute('href'))

In [97]:
#Writing and searching data science on this page
search_ds=driver.find_element_by_xpath("//input[@class='sugInp']")
search_ds.send_keys("Data Science")
driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']").click()

In [98]:
#Creating empty lists for storing scraped data
Name=[]
Des=[] 
Comp=[] 
Skill=[] 
Loc=[]

In [100]:
#Collecting the information of recruiters
name = driver.find_elements_by_xpath('//span[@class="fl ellipsis"]')
for i in name:
    Name.append(i.text)
designation = driver.find_elements_by_xpath('//span[@class="ellipsis clr"]')
for i in designation:
    Des.append(i.text)
company = driver.find_elements_by_xpath('//p[@class="highlightable"]/a[2]')
for i in company:
    Comp.append(i.text)
skill = driver.find_elements_by_xpath('//div[@class="hireSec highlightable"]')
for i in skill:
    Skill.append(i.text)
loc = driver.find_elements_by_xpath('//p[@class="highlightable"]/span[2]')
for i in loc:
    try:
        Loc.append(i.text)
    except NoSuchElementException:        
        Loc.append("------")

In [102]:
#Creating Dataframe for storing the collected data present in lists
Naukri_DS=pd.DataFrame({})
Naukri_DS['Name']=Name[0:48]
Naukri_DS['Designation']=Des[0:48]
Naukri_DS['Company']=Comp[0:48]
Naukri_DS['Skills they Hire for']= Skill[0:48]
Naukri_DS['Location']=Loc[0:48]

In [103]:
Naukri_DS

,Name,Designation,Company,Skills they Hire for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,Talent Acquisition Executive,Recruitment Professional,XenonStack,"Web Designing, html5, Angular.js, seo, hadoop,...",Chandigarh
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
5,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
6,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
7,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
8,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
9,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
10,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
11,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
12,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
14,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Nagpur
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
17,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
18,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
19,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
20,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
21,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
22,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
23,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
25,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
27,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Delhi
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Bengaluru / Bangalore
30,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
31,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learn...",Mysoru / Mysore
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Noida
33,Prateek Kumar,Head,Trisect,"Java, Python, Angularjs, Software Testing, Mac...",New Delhi
34,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",Chennai
35,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Aligarh
36,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Salt Lake City
37,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Pune
38,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Bengaluru / Bangalore
39,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Mumbai
40,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Indore
41,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Bengaluru / Bangalore
42,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",MYSORE
43,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",Hyderabad / Secunderabad
44,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Bengaluru / Bangalore
45,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Mumbai
46,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Hyderabad / Secunderabad
47,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",Noida

# 8. Scrape the details of Highest selling novels.

- Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/
- You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [104]:
#Connecting to web driver
driver = webdriver.Chrome(r"C://chromedriver.exe")
driver.maximize_window()

In [105]:
#Opening Naukri.com page
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/')
driver.implicitly_wait(5)

In [106]:
#Creating empty lists for storing scraped data
BName=[] 
AName=[] 
VSold=[]
Pub=[] 
Genre=[]

In [107]:
#Collecting the information of Books
book = driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[2]')
for i in book:
    BName.append(i.text)
author = driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[3]')
for i in author:
    AName.append(i.text)
vol = driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[4]')
for i in vol:
    VSold.append(i.text)
pub = driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[5]')
for i in pub:
    Pub.append(i.text)
gen = driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[6]')
for i in gen:
    Genre.append(i.text)

In [108]:
#Creating Dataframe for storing the collected data present in lists
Novels=pd.DataFrame({})
Novels['Book Name']=BName
Novels['Author Name']= AName
Novels['Volumes Sold']=VSold
Novels['Publisher']=Pub
Novels['Genre']=Genre

In [109]:
Novels

,Book Name,Author Name,Volumes Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# 9. Scrape the details most watched tv series of all time from imdb.com.

- Url = https://www.imdb.com/list/ls095964455/
- You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [110]:
#Connecting to web driver
driver = webdriver.Chrome(r"C://chromedriver.exe")
driver.maximize_window()

In [111]:
#Opening Naukri.com page
driver.get('https://www.imdb.com/list/ls095964455/')
driver.implicitly_wait(5)

In [112]:
#Creating empty lists for storing scraped data
Name=[]
Span=[] 
Genre=[] 
RTime=[] 
Ratings=[] 
Votes=[]

In [113]:
#Collecting the information about TV series
name = driver.find_elements_by_xpath('//h3[@class="lister-item-header"]/a')
for i in name:
    Name.append(i.text)
year = driver.find_elements_by_xpath('//span[@class="lister-item-year text-muted unbold"]')
for i in year:
    Span.append(i.text)
gen = driver.find_elements_by_xpath('//span[@class="genre"]')
for i in gen:
    Genre.append(i.text)
runtime = driver.find_elements_by_xpath('//span[@class="runtime"]')
for i in runtime:
    RTime.append(i.text)
ratings = driver.find_elements_by_xpath('//div[@class="ipl-rating-star small"]')
for i in ratings:
    Ratings.append(i.text)
vote = driver.find_elements_by_xpath('//span[@name="nv"]')
for i in vote:
    Votes.append(i.text)

In [114]:
#Creating Dataframe for storing the collected data present in lists
TopTV=pd.DataFrame({})
TopTV['Name']=Name
TopTV['Year Span']= Span
TopTV['Genre']=Genre
TopTV['Run Time']= RTime
TopTV['Ratings']=Ratings
TopTV['Votes']=Votes

In [115]:
TopTV

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.3,"1,805,390"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"849,983"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"868,873"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"260,582"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"221,589"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"44,268"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"54,720"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"165,829"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.2,"34,633"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"188,676"

# 10. Details of Datasets from UCI machine learning repositories.

- Url = https://archive.ics.uci.edu/
- You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
- Note: - from the home page you have to go to the Show All Dataset page through code.

In [120]:
#Connecting to web driver
driver = webdriver.Chrome(r"C://chromedriver.exe")
driver.maximize_window()

In [122]:
#Opening Naukri.com page
driver.get('https://archive.ics.uci.edu/')
driver.implicitly_wait(5)

WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT
  (Session info: chrome=90.0.4430.93)

Site under maintenance